export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SELECTED_PRODUCT = 'SELECTED_PRODUCT';
export const REMOVE_SELECTED_PRODUCT = 'REMOVE_SELECTED_PRODUCT';
export const SELECTED_PRODUCT_IDS = 'SELECTED_PRODUCT_IDS';
export const REMOVE_SELECTED_ID = 'REMOVE_SELECTED_ID';
export const SELECTED_PRODUCT_AddCart = 'SELECTED_PRODUCT_AddCart';
export const REMOVE_SELECTED_AddCart_PRODUCT = 'REMOVE_SELECTED_AddCart_PRODUCT';
export const SELECTED_PRODUCT_SAVELATER = 'SELECTED_PRODUCT_SAVELATER';
export const REMOVE_SELECTED_SAVELATER_PRODUCT = 'REMOVE_SELECTED_SAVELATER_PRODUCT';
export const Search_TERM = 'Search_TERM';
export const REMOVE_SELECTED_ID_MAIN = 'REMOVE_SELECTED_ID_MAIN';
export const THEME = 'THEME';

